name: rada
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

#dependencies:
 # flutter:
  #  sdk: flutter

dependencies:
  flutter_spinkit: "^4.1.2"
  toast: ^0.1.5
  bubble: ^1.1.9+1
  dash_chat: ^1.1.2
  flutter_local_notifications: '1.4.2'
  permission_handler: ^3.2.0
  flutter_sfsymbols: ^1.0.0
  awesome_page_transitions: ^1.0.0
  flutter_page_transition: ^0.1.6
  flare_loading: ^2.1.1
  progress_dialog:
  flutter_neumorphic: 3.0.2
  firebase_auth:
  cloud_firestore:
  argon_buttons_flutter: ^1.0.2
  flutter_styled_toast: ^1.3.2
  flutter_holo_date_picker: ^0.1.5
  flushbar: ^1.10.4
  cached_network_image: ^2.2.0+1
  flutter_chat_bubble: ^1.0.2
  firebase_storage: ^3.0.6
  firebase_messaging: '6.0.13'
  async: ^2.4.1
  swipe_gesture_recognizer: ^0.0.2
  shared_preferences: ^0.5.8
  emoji_picker:
  google_fonts: ^0.2.0
  flutter_awesome_buttons: ^0.1.0
  badges: ^1.1.1
  flutter_linkify: ^3.1.3
  url_launcher:
  sqflite: ^1.3.0
  path_provider: any
  carousel_slider: ^2.2.1
  flutter_stack_card: ^0.2.0+1
  readmore: ^1.0.0
  animate_do: ^1.7.2
  state_persistence: ^0.0.7
  youtube_player_flutter: ^7.0.0+7
  flutter_dialogflow: ^0.1.0
  add_thumbnail: ^0.0.2
  google_maps_flutter: ^0.5.30
  json_annotation: ^3.0.1
  #  connectivity: ^0.4.9
  connectivityswift: ^1.1.1+4
  link_text: ^0.1.2
  tts: ^1.0.1
  flutter_rating: ^0.0.2
  rating_dialog: ^1.0.0
  flutter_signin_button: ^1.0.0
  # Add the following two lines
  http: ^0.12.0+1
  json_serializable: ^3.3.0
  youtube_api: ^0.8.0
  timeline_list: ^0.0.3
  sleek_button: ^0.1.1
  dio:
  #  downloads_path_provider_28: ^0.1.0
  auto_direction: ^0.0.4+1
  chat_pickers: ^0.2.2
  swipe_to: ^0.0.1+3
  gallery_view: ^0.0.4
  esys_flutter_share: ^1.0.2
  file_picker: ^2.0.6
  video_thumbnail: ^0.2.2
  video_player: 0.11.0
  chewie:
  toggle_switch: ^0.1.8
  gallery_saver: ^2.0.1
  pusher_websocket_flutter: ^0.2.0
  loading: ^1.0.2
  focused_menu: ^1.0.1
  flutter_automation: ^1.1.4
 # flutter_launcher_icons: any
  ftoast: ^1.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/tower.jpg
    - assets/images/Loading.flr
    - assets/images/info.png
    - assets/images/knowledge.png
    - assets/images/counsellor.png
    - assets/images/forum.png
    - assets/images/settings.png
    - assets/images/information.png
    - assets/images/bell.png
    - assets/images/mentor.png
    - assets/images/idea.png
    - assets/images/exclamation.png
    - assets/images/flower.png
    - assets/images/time.png
    - assets/images/money.png
    - assets/images/video.png
    - assets/credentials/credentials.json
    - assets/images/rada1.jpg
    - assets/images/mentorship.png
    - assets/images/intro.jpg
    - assets/images/dating.jpg
    - assets/images/romance.jpg
    - assets/images/chat_bg.png
    - assets/images/chat_bg.jpg
    - assets/images/arrow.png
    - assets/images/image.png
    - assets/images/error.png
    - assets/images/rada_log.png
    - assets/images/love.png
    - assets/images/couple.png
    - assets/images/seku.jpeg
    - assets/images/college.jpeg
    - assets/images/seklogo.png
    - assets/images/selogo.png
    - assets/images/selogoho.png
    - assets/images/selogoh.png
    - assets/images/radase.png
    - assets/images/radasekudark.png
    - assets/images/serada.jpeg

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/UbuntuCondensed-Regular.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
